# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

top = '..'

def build(bld):
    bld.program(target='../unit-tests',
                name='unit-tests',
                source=(bld.path.ant_glob('**/*.cpp') +
                        bld.path.parent.ant_glob([
                            'ndn-service-framework/NDNSFMessages.cpp',
                            'ndn-service-framework/Service.cpp',
                            'ndn-service-framework/ServiceProvider.cpp',
                            'ndn-service-framework/ServiceStub.cpp',
                            'ndn-service-framework/ServiceUser.cpp',
                            'ndn-service-framework/utils.cpp',
                        ])),
                includes=['..', '../ndn-service-framework'],
                use='NDN_CXX NDN_SVS PROTOBUF NAC-ABE NDNSD BOOST',
                cxxflags=['-fPIC'],
                install_path=None)
