"""High-level distributed inference APIs built on NDNSF Python Core."""

from .app import (
    APPClient,
    APPController,
    APPDeployment,
    APPProvider,
    InferencePlanBuilder,
    ModelPart,
)
from .client import DeploymentSession, DistributedInferenceClient, InferenceResult
from .controller import DistributedInferenceController
from .plan import (
    ArtifactSpec,
    DependencyGraph,
    DistributedInferencePlan,
    DependencyEdge,
    InferenceDependency,
    InferenceRole,
    ModelFamily,
    ModelFormat,
    PlannerDescriptor,
    PlannerKind,
    RoleDependencyView,
    RuntimeSpec,
    nxm_stage_frontier_dependencies,
    nxm_stage_roles,
    stage_shard_role,
)
from .provider import (
    DistributedInferenceProvider,
    ProviderAdmissionPolicy,
    ProviderRuntimeContext,
)
from .repo import (
    DistributedRepo,
    LocalDistributedRepo,
    NetworkDistributedRepoClient,
    PlacementPolicy,
    RepoObjectManifest,
    RepoRepairAction,
    RepoPlacement,
    RepoNodeApp,
    StorageCapability,
    large_data_reference_from_repo_manifest,
    repo_artifact_reference,
    repo_manifest_from_artifact_reference,
    repo_manifest_from_large_data_reference,
    select_replicas,
)
from .runtime_compatibility import (
    RUNTIME_COMPATIBILITY,
    default_runtime_backend,
    supported_runtime_backends,
    validate_runtime_compatibility,
)
from .runtime_v1 import (
    CachePlacementDecision,
    BoundedDependencyTransferQueues,
    ContextObjectKind,
    ContextStateObject,
    DependencyTransferItem,
    DependencyTransferSnapshot,
    AdmissionLeaseStatus,
    DiFragmentRuntimeState,
    DiLeaseResourceBinding,
    DiProviderRuntimeState,
    ExactForwardCacheEntry,
    ExactForwardCacheKey,
    ExactForwardCacheKind,
    ExactForwardCacheManager,
    FailureAction,
    FallbackPlan,
    FragmentResidency,
    GenericAckMetadata,
    GenericAdmissionLease,
    GenericLeaseValidationResult,
    GenericProviderRuntimeHint,
    KvCacheTelemetry,
    LongContextManager,
    ModelFragmentKey,
    ModelManifestV1,
    PeerNetworkMetric,
    PlanDependency,
    PlanCache,
    PlanKeyV1,
    PlanLeaseV1,
    PlanRole,
    PlanTemplate,
    ProviderAdmissionLeaseTable,
    ProviderNetworkMatrix,
    ProviderProfileV1,
    ReplanRecord,
    RolePipelineScheduler,
    RoleWorkItem,
    RoleWorkSnapshot,
    RoleWorkStatus,
    RuntimeTelemetryV1,
    SemanticCacheAckHint,
    SemanticCacheDisposition,
    SemanticPatternMeta,
    SemanticPatternRank,
    SemanticServiceCacheEntry,
    SemanticServiceCacheKey,
    SemanticServiceCacheManager,
    TransferQueueKind,
    RetryPolicy,
    adaptive_segment_size,
    build_local_llm_plan,
    choose_cache_placement,
    choose_edge_aware_runtime_assignment,
    choose_bounded_replan_assignment,
    choose_runtime_assignment,
    choose_semantic_cache_provider,
    compress_payload,
    encode_ack_metadata,
    exact_forward_cache_key_for_stage,
    exact_token_prefix_digest,
    export_telemetry_csv,
    generation_chunk,
    generate_fallback_plans,
    kv_block,
    load_provider_profiles,
    make_plan_lease,
    parse_ack_metadata,
    parse_semantic_cache_ack_hint,
    prefix_state,
    prompt_chunk,
    proportional_layer_allocation,
    residency_ready_cost_ms,
    rank_semantic_patterns,
    runtime_v1_smoke,
    session_state,
    semantic_cache_ack_fields,
    semantic_cache_token_saving_ratio,
    simulate_prefill_decode,
    stage_definition_from_plan_stage,
    to_plain,
    validate_linear_llm_plan,
    write_json,
    write_runtime_report,
)
from .runtime_v1_evidence import write_minindn_runtime_v1_evidence
from .artifact_deployment import (
    ArtifactProvisioningState,
    MaterializedArtifact,
    artifact_references_need_repo_client,
    load_artifact_references,
    materialize_role_artifacts,
    materialized_path,
    role_artifact_entries,
)
from .llm_stub_planner import (
    LLM_RUNTIME_COMPATIBILITY,
    default_llm_runtime_backend,
    llm_planner_registry,
    llm_planner_request,
    llm_splitter_output_from_result,
    llm_supported_runtime_backends,
    llm_stub_plan_from_request,
    validate_llm_runtime_compatibility,
)
from .llm_runtime import (
    ManagedLlamaServerRuntime,
    OpenAIChatRequest,
    OpenAICompatibleChatRuntime,
    call_openai_chat_runtime,
    decode_openai_chat_response,
    encode_openai_chat_request,
    materialize_llm_runtime_artifacts,
)
from .onnx_graph import (
    OnnxChunkSpec,
    OnnxGraphSummary,
    OnnxSplitCandidate,
    analyze_onnx_graph,
    build_chunk_dependencies,
    build_sequential_chunk_dependencies,
    estimate_split_candidates,
    write_onnx_graph_summary,
)
try:
    from .onnx_executor import (
        OnnxExecutionResult,
        decode_tensor_bundle,
        encode_tensor_bundle,
        execute_onnx_dependency_chunk,
        load_npz_payload,
        npz_payload,
        prefetch_dependency_inputs,
        role_topic_token,
        select_tensor_payload,
        verify_tensor_payload,
    )
except ImportError as exc:  # pragma: no cover - optional ONNX runtime path
    _onnx_executor_import_error = exc

    class OnnxExecutionResult:  # type: ignore[no-redef]
        pass

    def _missing_onnx_executor(*args, **kwargs):
        raise ImportError(
            "ONNX executor support requires optional ONNX runtime dependencies"
        ) from _onnx_executor_import_error

    decode_tensor_bundle = _missing_onnx_executor
    encode_tensor_bundle = _missing_onnx_executor
    execute_onnx_dependency_chunk = _missing_onnx_executor
    load_npz_payload = _missing_onnx_executor
    npz_payload = _missing_onnx_executor
    prefetch_dependency_inputs = _missing_onnx_executor
    role_topic_token = _missing_onnx_executor
    select_tensor_payload = _missing_onnx_executor
    verify_tensor_payload = _missing_onnx_executor
from .policy import (
    ArtifactSecurityPolicy,
    DistributedInferenceDeployment,
    SandboxPolicy,
    load_config,
    load_or_generate_deployment,
    native_execution_plan_spec,
    write_policy_bundle,
)
from .planner_registry import (
    PlannerBackend,
    PlannerBackendRegistry,
    PlannerRequest,
    PlannerResult,
    default_planner_registry,
)
from .split_planner import (
    ProviderProfile,
    SequentialSplitCandidate,
    SplitPlanRecommendation,
    SplitPlannerWeights,
    homogeneous_provider_profiles,
    recommend_sequential_splits,
)
from .splitter import SplitArtifact, SplitServiceSpec, SplitterOutput
try:
    from py_repoclient import RepoClient as GenericRepoClient
except ImportError:  # pragma: no cover - optional when repo binding is not installed
    GenericRepoClient = None

__all__ = [
    "ArtifactProvisioningState",
    "ArtifactSpec",
    "ArtifactSecurityPolicy",
    "APPClient",
    "APPController",
    "APPDeployment",
    "APPProvider",
    "DistributedInferenceClient",
    "DistributedInferenceController",
    "DistributedInferencePlan",
    "DistributedInferenceProvider",
    "DistributedRepo",
    "DistributedInferenceDeployment",
    "DeploymentSession",
    "DependencyGraph",
    "DependencyEdge",
    "InferenceDependency",
    "InferencePlanBuilder",
    "InferenceResult",
    "InferenceRole",
    "GenericRepoClient",
    "MaterializedArtifact",
    "ManagedLlamaServerRuntime",
    "ModelPart",
    "ModelFamily",
    "ModelFormat",
    "PlannerDescriptor",
    "PlannerBackend",
    "PlannerBackendRegistry",
    "PlannerKind",
    "PlannerRequest",
    "PlannerResult",
    "ProviderAdmissionPolicy",
    "ProviderRuntimeContext",
    "LocalDistributedRepo",
    "OpenAIChatRequest",
    "OpenAICompatibleChatRuntime",
    "RUNTIME_COMPATIBILITY",
    "default_runtime_backend",
    "supported_runtime_backends",
    "validate_runtime_compatibility",
    "LLM_RUNTIME_COMPATIBILITY",
    "default_llm_runtime_backend",
    "llm_planner_registry",
    "llm_planner_request",
    "llm_splitter_output_from_result",
    "llm_supported_runtime_backends",
    "llm_stub_plan_from_request",
    "NetworkDistributedRepoClient",
    "OnnxChunkSpec",
    "OnnxGraphSummary",
    "OnnxExecutionResult",
    "OnnxSplitCandidate",
    "PlacementPolicy",
    "ProviderProfile",
    "RepoObjectManifest",
    "RepoRepairAction",
    "RepoNodeApp",
    "RepoPlacement",
    "large_data_reference_from_repo_manifest",
    "artifact_references_need_repo_client",
    "call_openai_chat_runtime",
    "decode_openai_chat_response",
    "encode_openai_chat_request",
    "load_artifact_references",
    "materialize_llm_runtime_artifacts",
    "materialize_role_artifacts",
    "materialized_path",
    "repo_artifact_reference",
    "repo_manifest_from_artifact_reference",
    "repo_manifest_from_large_data_reference",
    "role_artifact_entries",
    "RoleDependencyView",
    "RuntimeSpec",
    "SandboxPolicy",
    "SequentialSplitCandidate",
    "SplitArtifact",
    "SplitServiceSpec",
    "SplitPlanRecommendation",
    "SplitPlannerWeights",
    "SplitterOutput",
    "StorageCapability",
    "analyze_onnx_graph",
    "build_chunk_dependencies",
    "build_sequential_chunk_dependencies",
    "decode_tensor_bundle",
    "encode_tensor_bundle",
    "execute_onnx_dependency_chunk",
    "estimate_split_candidates",
    "default_planner_registry",
    "homogeneous_provider_profiles",
    "load_npz_payload",
    "load_config",
    "load_or_generate_deployment",
    "native_execution_plan_spec",
    "npz_payload",
    "nxm_stage_frontier_dependencies",
    "nxm_stage_roles",
    "prefetch_dependency_inputs",
    "recommend_sequential_splits",
    "role_topic_token",
    "select_replicas",
    "select_tensor_payload",
    "stage_shard_role",
    "validate_llm_runtime_compatibility",
    "verify_tensor_payload",
    "write_onnx_graph_summary",
    "write_policy_bundle",
]

__all__ += [
    "CachePlacementDecision",
    "BoundedDependencyTransferQueues",
    "ContextObjectKind",
    "ContextStateObject",
    "DependencyTransferItem",
    "DependencyTransferSnapshot",
    "ExactForwardCacheEntry",
    "ExactForwardCacheKey",
    "ExactForwardCacheKind",
    "ExactForwardCacheManager",
    "FailureAction",
    "FallbackPlan",
    "KvCacheTelemetry",
    "LongContextManager",
    "ModelManifestV1",
    "PlanCache",
    "PlanKeyV1",
    "PlanLeaseV1",
    "ProviderProfileV1",
    "RolePipelineScheduler",
    "RoleWorkItem",
    "RoleWorkSnapshot",
    "RoleWorkStatus",
    "RuntimeTelemetryV1",
    "SemanticCacheAckHint",
    "SemanticCacheDisposition",
    "SemanticPatternMeta",
    "SemanticPatternRank",
    "SemanticServiceCacheEntry",
    "SemanticServiceCacheKey",
    "SemanticServiceCacheManager",
    "RetryPolicy",
    "TransferQueueKind",
    "adaptive_segment_size",
    "build_local_llm_plan",
    "choose_cache_placement",
    "choose_semantic_cache_provider",
    "compress_payload",
    "encode_ack_metadata",
    "exact_forward_cache_key_for_stage",
    "exact_token_prefix_digest",
    "export_telemetry_csv",
    "generation_chunk",
    "generate_fallback_plans",
    "kv_block",
    "load_provider_profiles",
    "make_plan_lease",
    "parse_ack_metadata",
    "parse_semantic_cache_ack_hint",
    "prefix_state",
    "prompt_chunk",
    "proportional_layer_allocation",
    "rank_semantic_patterns",
    "runtime_v1_smoke",
    "session_state",
    "semantic_cache_ack_fields",
    "semantic_cache_token_saving_ratio",
    "simulate_prefill_decode",
    "stage_definition_from_plan_stage",
    "validate_linear_llm_plan",
    "write_runtime_report",
    "write_minindn_runtime_v1_evidence",
]
