"""High-level distributed inference APIs built on NDNSF Python Core."""

from .app import (
    APPClient,
    APPController,
    APPDeployment,
    APPProvider,
    InferencePlanBuilder,
    ModelPart,
)
from .client import DistributedInferenceClient, InferenceResult
from .controller import DistributedInferenceController
from .plan import (
    ArtifactSpec,
    DependencyGraph,
    DistributedInferencePlan,
    DependencyEdge,
    InferenceDependency,
    InferenceRole,
    RoleDependencyView,
    RuntimeSpec,
)
from .provider import DistributedInferenceProvider, ProviderRuntimeContext
from .repo import (
    DistributedRepo,
    LocalDistributedRepo,
    NetworkDistributedRepoClient,
    PlacementPolicy,
    RepoObjectManifest,
    RepoPlacement,
    RepoNodeApp,
    StorageCapability,
    select_replicas,
)
from .onnx_graph import (
    OnnxChunkSpec,
    OnnxGraphSummary,
    OnnxSplitCandidate,
    analyze_onnx_graph,
    build_chunk_dependencies,
    build_sequential_chunk_dependencies,
    estimate_split_candidates,
    write_onnx_graph_summary,
)
from .onnx_executor import (
    OnnxExecutionResult,
    decode_tensor_bundle,
    encode_tensor_bundle,
    execute_onnx_dependency_chunk,
    load_npz_payload,
    npz_payload,
    prefetch_dependency_inputs,
    role_topic_token,
    select_tensor_payload,
    verify_tensor_payload,
)
from .policy import (
    ArtifactSecurityPolicy,
    DistributedInferenceDeployment,
    SandboxPolicy,
    load_config,
    load_or_generate_deployment,
    write_policy_bundle,
)
from .split_planner import (
    ProviderProfile,
    SequentialSplitCandidate,
    SplitPlanRecommendation,
    SplitPlannerWeights,
    homogeneous_provider_profiles,
    recommend_sequential_splits,
)
from .splitter import SplitArtifact, SplitServiceSpec, SplitterOutput
try:
    from py_repoclient import RepoClient as GenericRepoClient
except ImportError:  # pragma: no cover - optional when repo binding is not installed
    GenericRepoClient = None

__all__ = [
    "ArtifactSpec",
    "ArtifactSecurityPolicy",
    "APPClient",
    "APPController",
    "APPDeployment",
    "APPProvider",
    "DistributedInferenceClient",
    "DistributedInferenceController",
    "DistributedInferencePlan",
    "DistributedInferenceProvider",
    "DistributedRepo",
    "DistributedInferenceDeployment",
    "DependencyGraph",
    "DependencyEdge",
    "InferenceDependency",
    "InferencePlanBuilder",
    "InferenceResult",
    "InferenceRole",
    "GenericRepoClient",
    "ModelPart",
    "ProviderRuntimeContext",
    "LocalDistributedRepo",
    "NetworkDistributedRepoClient",
    "OnnxChunkSpec",
    "OnnxGraphSummary",
    "OnnxExecutionResult",
    "OnnxSplitCandidate",
    "PlacementPolicy",
    "ProviderProfile",
    "RepoObjectManifest",
    "RepoNodeApp",
    "RepoPlacement",
    "RoleDependencyView",
    "RuntimeSpec",
    "SandboxPolicy",
    "SequentialSplitCandidate",
    "SplitArtifact",
    "SplitServiceSpec",
    "SplitPlanRecommendation",
    "SplitPlannerWeights",
    "SplitterOutput",
    "StorageCapability",
    "analyze_onnx_graph",
    "build_chunk_dependencies",
    "build_sequential_chunk_dependencies",
    "decode_tensor_bundle",
    "encode_tensor_bundle",
    "execute_onnx_dependency_chunk",
    "estimate_split_candidates",
    "homogeneous_provider_profiles",
    "load_npz_payload",
    "load_config",
    "load_or_generate_deployment",
    "npz_payload",
    "prefetch_dependency_inputs",
    "recommend_sequential_splits",
    "role_topic_token",
    "select_replicas",
    "select_tensor_payload",
    "verify_tensor_payload",
    "write_onnx_graph_summary",
    "write_policy_bundle",
]
