[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
[project]
name = "ndnsf-di-adapter-llama"
version = "0.111.0"
dependencies = ["ndnsf-di-sdk==0.111.0"]
[tool.setuptools.packages.find]
where = ["../../../.."]
include = ["ndnsf_distributed_inference.adapters.llama*"]
