[nodes]
gs:
scout-a:
scout-b:
compute:

[links]
gs:scout-a delay=2ms bw=1000
gs:scout-b delay=2ms bw=1000
gs:compute delay=2ms bw=1000

[faces]
gs:scout-a cost=10
gs:scout-b cost=10
gs:compute cost=10
