// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: onnx/onnx-data.proto

#include "onnx/onnx-data.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_onnx_2fonnx_2ddata_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_onnx_2fonnx_2ddata_2eproto ::google::protobuf::internal::SCCInfo<2> scc_info_MapProto;
}  // namespace protobuf_onnx_2fonnx_2ddata_2eproto
namespace protobuf_onnx_2fonnx_2dml_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_onnx_2fonnx_2dml_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_SparseTensorProto;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_onnx_2fonnx_2dml_2eproto ::google::protobuf::internal::SCCInfo<2> scc_info_TensorProto;
}  // namespace protobuf_onnx_2fonnx_2dml_2eproto
namespace onnx {
class SequenceProtoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SequenceProto>
      _instance;
} _SequenceProto_default_instance_;
class MapProtoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MapProto>
      _instance;
} _MapProto_default_instance_;
class OptionalProtoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<OptionalProto>
      _instance;
} _OptionalProto_default_instance_;
}  // namespace onnx
namespace protobuf_onnx_2fonnx_2ddata_2eproto {
static void InitDefaultsMapProto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::onnx::_SequenceProto_default_instance_;
    new (ptr) ::onnx::SequenceProto();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  {
    void* ptr = &::onnx::_MapProto_default_instance_;
    new (ptr) ::onnx::MapProto();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  {
    void* ptr = &::onnx::_OptionalProto_default_instance_;
    new (ptr) ::onnx::OptionalProto();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::onnx::SequenceProto::InitAsDefaultInstance();
  ::onnx::MapProto::InitAsDefaultInstance();
  ::onnx::OptionalProto::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_MapProto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsMapProto}, {
      &protobuf_onnx_2fonnx_2dml_2eproto::scc_info_TensorProto.base,
      &protobuf_onnx_2fonnx_2dml_2eproto::scc_info_SparseTensorProto.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_MapProto.base);
}

}  // namespace protobuf_onnx_2fonnx_2ddata_2eproto
namespace onnx {
bool SequenceProto_DataType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const SequenceProto_DataType SequenceProto::UNDEFINED;
const SequenceProto_DataType SequenceProto::TENSOR;
const SequenceProto_DataType SequenceProto::SPARSE_TENSOR;
const SequenceProto_DataType SequenceProto::SEQUENCE;
const SequenceProto_DataType SequenceProto::MAP;
const SequenceProto_DataType SequenceProto::OPTIONAL;
const SequenceProto_DataType SequenceProto::DataType_MIN;
const SequenceProto_DataType SequenceProto::DataType_MAX;
const int SequenceProto::DataType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
bool OptionalProto_DataType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const OptionalProto_DataType OptionalProto::UNDEFINED;
const OptionalProto_DataType OptionalProto::TENSOR;
const OptionalProto_DataType OptionalProto::SPARSE_TENSOR;
const OptionalProto_DataType OptionalProto::SEQUENCE;
const OptionalProto_DataType OptionalProto::MAP;
const OptionalProto_DataType OptionalProto::OPTIONAL;
const OptionalProto_DataType OptionalProto::DataType_MIN;
const OptionalProto_DataType OptionalProto::DataType_MAX;
const int OptionalProto::DataType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

void SequenceProto::InitAsDefaultInstance() {
}
void SequenceProto::clear_tensor_values() {
  tensor_values_.Clear();
}
void SequenceProto::clear_sparse_tensor_values() {
  sparse_tensor_values_.Clear();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SequenceProto::kNameFieldNumber;
const int SequenceProto::kElemTypeFieldNumber;
const int SequenceProto::kTensorValuesFieldNumber;
const int SequenceProto::kSparseTensorValuesFieldNumber;
const int SequenceProto::kSequenceValuesFieldNumber;
const int SequenceProto::kMapValuesFieldNumber;
const int SequenceProto::kOptionalValuesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SequenceProto::SequenceProto()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_onnx_2fonnx_2ddata_2eproto::scc_info_MapProto.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:onnx.SequenceProto)
}
SequenceProto::SequenceProto(const SequenceProto& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      tensor_values_(from.tensor_values_),
      sparse_tensor_values_(from.sparse_tensor_values_),
      sequence_values_(from.sequence_values_),
      map_values_(from.map_values_),
      optional_values_(from.optional_values_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_name()) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  elem_type_ = from.elem_type_;
  // @@protoc_insertion_point(copy_constructor:onnx.SequenceProto)
}

void SequenceProto::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  elem_type_ = 0;
}

SequenceProto::~SequenceProto() {
  // @@protoc_insertion_point(destructor:onnx.SequenceProto)
  SharedDtor();
}

void SequenceProto::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void SequenceProto::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SequenceProto& SequenceProto::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_onnx_2fonnx_2ddata_2eproto::scc_info_MapProto.base);
  return *internal_default_instance();
}


void SequenceProto::Clear() {
// @@protoc_insertion_point(message_clear_start:onnx.SequenceProto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  tensor_values_.Clear();
  sparse_tensor_values_.Clear();
  sequence_values_.Clear();
  map_values_.Clear();
  optional_values_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    name_.ClearNonDefaultToEmptyNoArena();
  }
  elem_type_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool SequenceProto::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:onnx.SequenceProto)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 elem_type = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          set_has_elem_type();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &elem_type_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .onnx.TensorProto tensor_values = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_tensor_values()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .onnx.SparseTensorProto sparse_tensor_values = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_sparse_tensor_values()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .onnx.SequenceProto sequence_values = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_sequence_values()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .onnx.MapProto map_values = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_map_values()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .onnx.OptionalProto optional_values = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_optional_values()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:onnx.SequenceProto)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:onnx.SequenceProto)
  return false;
#undef DO_
}

void SequenceProto::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:onnx.SequenceProto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // optional int32 elem_type = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->elem_type(), output);
  }

  // repeated .onnx.TensorProto tensor_values = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->tensor_values_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      3,
      this->tensor_values(static_cast<int>(i)),
      output);
  }

  // repeated .onnx.SparseTensorProto sparse_tensor_values = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->sparse_tensor_values_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      4,
      this->sparse_tensor_values(static_cast<int>(i)),
      output);
  }

  // repeated .onnx.SequenceProto sequence_values = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->sequence_values_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      5,
      this->sequence_values(static_cast<int>(i)),
      output);
  }

  // repeated .onnx.MapProto map_values = 6;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->map_values_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      6,
      this->map_values(static_cast<int>(i)),
      output);
  }

  // repeated .onnx.OptionalProto optional_values = 7;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->optional_values_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      7,
      this->optional_values(static_cast<int>(i)),
      output);
  }

  output->WriteRaw(_internal_metadata_.unknown_fields().data(),
                   static_cast<int>(_internal_metadata_.unknown_fields().size()));
  // @@protoc_insertion_point(serialize_end:onnx.SequenceProto)
}

size_t SequenceProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:onnx.SequenceProto)
  size_t total_size = 0;

  total_size += _internal_metadata_.unknown_fields().size();

  // repeated .onnx.TensorProto tensor_values = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->tensor_values_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->tensor_values(static_cast<int>(i)));
    }
  }

  // repeated .onnx.SparseTensorProto sparse_tensor_values = 4;
  {
    unsigned int count = static_cast<unsigned int>(this->sparse_tensor_values_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->sparse_tensor_values(static_cast<int>(i)));
    }
  }

  // repeated .onnx.SequenceProto sequence_values = 5;
  {
    unsigned int count = static_cast<unsigned int>(this->sequence_values_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->sequence_values(static_cast<int>(i)));
    }
  }

  // repeated .onnx.MapProto map_values = 6;
  {
    unsigned int count = static_cast<unsigned int>(this->map_values_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->map_values(static_cast<int>(i)));
    }
  }

  // repeated .onnx.OptionalProto optional_values = 7;
  {
    unsigned int count = static_cast<unsigned int>(this->optional_values_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->optional_values(static_cast<int>(i)));
    }
  }

  if (_has_bits_[0 / 32] & 3u) {
    // optional string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

    // optional int32 elem_type = 2;
    if (has_elem_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->elem_type());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SequenceProto::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const SequenceProto*>(&from));
}

void SequenceProto::MergeFrom(const SequenceProto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:onnx.SequenceProto)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  tensor_values_.MergeFrom(from.tensor_values_);
  sparse_tensor_values_.MergeFrom(from.sparse_tensor_values_);
  sequence_values_.MergeFrom(from.sequence_values_);
  map_values_.MergeFrom(from.map_values_);
  optional_values_.MergeFrom(from.optional_values_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_name();
      name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
    }
    if (cached_has_bits & 0x00000002u) {
      elem_type_ = from.elem_type_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void SequenceProto::CopyFrom(const SequenceProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:onnx.SequenceProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SequenceProto::IsInitialized() const {
  return true;
}

void SequenceProto::Swap(SequenceProto* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SequenceProto::InternalSwap(SequenceProto* other) {
  using std::swap;
  CastToBase(&tensor_values_)->InternalSwap(CastToBase(&other->tensor_values_));
  CastToBase(&sparse_tensor_values_)->InternalSwap(CastToBase(&other->sparse_tensor_values_));
  CastToBase(&sequence_values_)->InternalSwap(CastToBase(&other->sequence_values_));
  CastToBase(&map_values_)->InternalSwap(CastToBase(&other->map_values_));
  CastToBase(&optional_values_)->InternalSwap(CastToBase(&other->optional_values_));
  name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(elem_type_, other->elem_type_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string SequenceProto::GetTypeName() const {
  return "onnx.SequenceProto";
}


// ===================================================================

void MapProto::InitAsDefaultInstance() {
  ::onnx::_MapProto_default_instance_._instance.get_mutable()->values_ = const_cast< ::onnx::SequenceProto*>(
      ::onnx::SequenceProto::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MapProto::kNameFieldNumber;
const int MapProto::kKeyTypeFieldNumber;
const int MapProto::kKeysFieldNumber;
const int MapProto::kStringKeysFieldNumber;
const int MapProto::kValuesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MapProto::MapProto()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_onnx_2fonnx_2ddata_2eproto::scc_info_MapProto.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:onnx.MapProto)
}
MapProto::MapProto(const MapProto& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      keys_(from.keys_),
      string_keys_(from.string_keys_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_name()) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.has_values()) {
    values_ = new ::onnx::SequenceProto(*from.values_);
  } else {
    values_ = NULL;
  }
  key_type_ = from.key_type_;
  // @@protoc_insertion_point(copy_constructor:onnx.MapProto)
}

void MapProto::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&values_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&key_type_) -
      reinterpret_cast<char*>(&values_)) + sizeof(key_type_));
}

MapProto::~MapProto() {
  // @@protoc_insertion_point(destructor:onnx.MapProto)
  SharedDtor();
}

void MapProto::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete values_;
}

void MapProto::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const MapProto& MapProto::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_onnx_2fonnx_2ddata_2eproto::scc_info_MapProto.base);
  return *internal_default_instance();
}


void MapProto::Clear() {
// @@protoc_insertion_point(message_clear_start:onnx.MapProto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  keys_.Clear();
  string_keys_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      name_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(values_ != NULL);
      values_->Clear();
    }
  }
  key_type_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool MapProto::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:onnx.MapProto)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 key_type = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          set_has_key_type();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &key_type_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated int64 keys = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 1, 24u, input, this->mutable_keys())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, this->mutable_keys())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated bytes string_keys = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->add_string_keys()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .onnx.SequenceProto values = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_values()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:onnx.MapProto)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:onnx.MapProto)
  return false;
#undef DO_
}

void MapProto::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:onnx.MapProto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // optional int32 key_type = 2;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->key_type(), output);
  }

  // repeated int64 keys = 3;
  for (int i = 0, n = this->keys_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(
      3, this->keys(i), output);
  }

  // repeated bytes string_keys = 4;
  for (int i = 0, n = this->string_keys_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      4, this->string_keys(i), output);
  }

  // optional .onnx.SequenceProto values = 5;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      5, this->_internal_values(), output);
  }

  output->WriteRaw(_internal_metadata_.unknown_fields().data(),
                   static_cast<int>(_internal_metadata_.unknown_fields().size()));
  // @@protoc_insertion_point(serialize_end:onnx.MapProto)
}

size_t MapProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:onnx.MapProto)
  size_t total_size = 0;

  total_size += _internal_metadata_.unknown_fields().size();

  // repeated int64 keys = 3;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int64Size(this->keys_);
    total_size += 1 *
                  ::google::protobuf::internal::FromIntSize(this->keys_size());
    total_size += data_size;
  }

  // repeated bytes string_keys = 4;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->string_keys_size());
  for (int i = 0, n = this->string_keys_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::BytesSize(
      this->string_keys(i));
  }

  if (_has_bits_[0 / 32] & 7u) {
    // optional string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

    // optional .onnx.SequenceProto values = 5;
    if (has_values()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *values_);
    }

    // optional int32 key_type = 2;
    if (has_key_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->key_type());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MapProto::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const MapProto*>(&from));
}

void MapProto::MergeFrom(const MapProto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:onnx.MapProto)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  keys_.MergeFrom(from.keys_);
  string_keys_.MergeFrom(from.string_keys_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 7u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_name();
      name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
    }
    if (cached_has_bits & 0x00000002u) {
      mutable_values()->::onnx::SequenceProto::MergeFrom(from.values());
    }
    if (cached_has_bits & 0x00000004u) {
      key_type_ = from.key_type_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void MapProto::CopyFrom(const MapProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:onnx.MapProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MapProto::IsInitialized() const {
  return true;
}

void MapProto::Swap(MapProto* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MapProto::InternalSwap(MapProto* other) {
  using std::swap;
  keys_.InternalSwap(&other->keys_);
  string_keys_.InternalSwap(CastToBase(&other->string_keys_));
  name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(values_, other->values_);
  swap(key_type_, other->key_type_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string MapProto::GetTypeName() const {
  return "onnx.MapProto";
}


// ===================================================================

void OptionalProto::InitAsDefaultInstance() {
  ::onnx::_OptionalProto_default_instance_._instance.get_mutable()->tensor_value_ = const_cast< ::onnx::TensorProto*>(
      ::onnx::TensorProto::internal_default_instance());
  ::onnx::_OptionalProto_default_instance_._instance.get_mutable()->sparse_tensor_value_ = const_cast< ::onnx::SparseTensorProto*>(
      ::onnx::SparseTensorProto::internal_default_instance());
  ::onnx::_OptionalProto_default_instance_._instance.get_mutable()->sequence_value_ = const_cast< ::onnx::SequenceProto*>(
      ::onnx::SequenceProto::internal_default_instance());
  ::onnx::_OptionalProto_default_instance_._instance.get_mutable()->map_value_ = const_cast< ::onnx::MapProto*>(
      ::onnx::MapProto::internal_default_instance());
  ::onnx::_OptionalProto_default_instance_._instance.get_mutable()->optional_value_ = const_cast< ::onnx::OptionalProto*>(
      ::onnx::OptionalProto::internal_default_instance());
}
void OptionalProto::clear_tensor_value() {
  if (tensor_value_ != NULL) tensor_value_->Clear();
  clear_has_tensor_value();
}
void OptionalProto::clear_sparse_tensor_value() {
  if (sparse_tensor_value_ != NULL) sparse_tensor_value_->Clear();
  clear_has_sparse_tensor_value();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int OptionalProto::kNameFieldNumber;
const int OptionalProto::kElemTypeFieldNumber;
const int OptionalProto::kTensorValueFieldNumber;
const int OptionalProto::kSparseTensorValueFieldNumber;
const int OptionalProto::kSequenceValueFieldNumber;
const int OptionalProto::kMapValueFieldNumber;
const int OptionalProto::kOptionalValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

OptionalProto::OptionalProto()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_onnx_2fonnx_2ddata_2eproto::scc_info_MapProto.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:onnx.OptionalProto)
}
OptionalProto::OptionalProto(const OptionalProto& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_name()) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.has_tensor_value()) {
    tensor_value_ = new ::onnx::TensorProto(*from.tensor_value_);
  } else {
    tensor_value_ = NULL;
  }
  if (from.has_sparse_tensor_value()) {
    sparse_tensor_value_ = new ::onnx::SparseTensorProto(*from.sparse_tensor_value_);
  } else {
    sparse_tensor_value_ = NULL;
  }
  if (from.has_sequence_value()) {
    sequence_value_ = new ::onnx::SequenceProto(*from.sequence_value_);
  } else {
    sequence_value_ = NULL;
  }
  if (from.has_map_value()) {
    map_value_ = new ::onnx::MapProto(*from.map_value_);
  } else {
    map_value_ = NULL;
  }
  if (from.has_optional_value()) {
    optional_value_ = new ::onnx::OptionalProto(*from.optional_value_);
  } else {
    optional_value_ = NULL;
  }
  elem_type_ = from.elem_type_;
  // @@protoc_insertion_point(copy_constructor:onnx.OptionalProto)
}

void OptionalProto::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&tensor_value_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&elem_type_) -
      reinterpret_cast<char*>(&tensor_value_)) + sizeof(elem_type_));
}

OptionalProto::~OptionalProto() {
  // @@protoc_insertion_point(destructor:onnx.OptionalProto)
  SharedDtor();
}

void OptionalProto::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete tensor_value_;
  if (this != internal_default_instance()) delete sparse_tensor_value_;
  if (this != internal_default_instance()) delete sequence_value_;
  if (this != internal_default_instance()) delete map_value_;
  if (this != internal_default_instance()) delete optional_value_;
}

void OptionalProto::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const OptionalProto& OptionalProto::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_onnx_2fonnx_2ddata_2eproto::scc_info_MapProto.base);
  return *internal_default_instance();
}


void OptionalProto::Clear() {
// @@protoc_insertion_point(message_clear_start:onnx.OptionalProto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 63u) {
    if (cached_has_bits & 0x00000001u) {
      name_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(tensor_value_ != NULL);
      tensor_value_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(sparse_tensor_value_ != NULL);
      sparse_tensor_value_->Clear();
    }
    if (cached_has_bits & 0x00000008u) {
      GOOGLE_DCHECK(sequence_value_ != NULL);
      sequence_value_->Clear();
    }
    if (cached_has_bits & 0x00000010u) {
      GOOGLE_DCHECK(map_value_ != NULL);
      map_value_->Clear();
    }
    if (cached_has_bits & 0x00000020u) {
      GOOGLE_DCHECK(optional_value_ != NULL);
      optional_value_->Clear();
    }
  }
  elem_type_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool OptionalProto::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:onnx.OptionalProto)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 elem_type = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          set_has_elem_type();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &elem_type_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .onnx.TensorProto tensor_value = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_tensor_value()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .onnx.SparseTensorProto sparse_tensor_value = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_sparse_tensor_value()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .onnx.SequenceProto sequence_value = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_sequence_value()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .onnx.MapProto map_value = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_map_value()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .onnx.OptionalProto optional_value = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_optional_value()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:onnx.OptionalProto)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:onnx.OptionalProto)
  return false;
#undef DO_
}

void OptionalProto::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:onnx.OptionalProto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // optional int32 elem_type = 2;
  if (cached_has_bits & 0x00000040u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->elem_type(), output);
  }

  // optional .onnx.TensorProto tensor_value = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      3, this->_internal_tensor_value(), output);
  }

  // optional .onnx.SparseTensorProto sparse_tensor_value = 4;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      4, this->_internal_sparse_tensor_value(), output);
  }

  // optional .onnx.SequenceProto sequence_value = 5;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      5, this->_internal_sequence_value(), output);
  }

  // optional .onnx.MapProto map_value = 6;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      6, this->_internal_map_value(), output);
  }

  // optional .onnx.OptionalProto optional_value = 7;
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      7, this->_internal_optional_value(), output);
  }

  output->WriteRaw(_internal_metadata_.unknown_fields().data(),
                   static_cast<int>(_internal_metadata_.unknown_fields().size()));
  // @@protoc_insertion_point(serialize_end:onnx.OptionalProto)
}

size_t OptionalProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:onnx.OptionalProto)
  size_t total_size = 0;

  total_size += _internal_metadata_.unknown_fields().size();

  if (_has_bits_[0 / 32] & 127u) {
    // optional string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

    // optional .onnx.TensorProto tensor_value = 3;
    if (has_tensor_value()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *tensor_value_);
    }

    // optional .onnx.SparseTensorProto sparse_tensor_value = 4;
    if (has_sparse_tensor_value()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *sparse_tensor_value_);
    }

    // optional .onnx.SequenceProto sequence_value = 5;
    if (has_sequence_value()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *sequence_value_);
    }

    // optional .onnx.MapProto map_value = 6;
    if (has_map_value()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *map_value_);
    }

    // optional .onnx.OptionalProto optional_value = 7;
    if (has_optional_value()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *optional_value_);
    }

    // optional int32 elem_type = 2;
    if (has_elem_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->elem_type());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void OptionalProto::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const OptionalProto*>(&from));
}

void OptionalProto::MergeFrom(const OptionalProto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:onnx.OptionalProto)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 127u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_name();
      name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
    }
    if (cached_has_bits & 0x00000002u) {
      mutable_tensor_value()->::onnx::TensorProto::MergeFrom(from.tensor_value());
    }
    if (cached_has_bits & 0x00000004u) {
      mutable_sparse_tensor_value()->::onnx::SparseTensorProto::MergeFrom(from.sparse_tensor_value());
    }
    if (cached_has_bits & 0x00000008u) {
      mutable_sequence_value()->::onnx::SequenceProto::MergeFrom(from.sequence_value());
    }
    if (cached_has_bits & 0x00000010u) {
      mutable_map_value()->::onnx::MapProto::MergeFrom(from.map_value());
    }
    if (cached_has_bits & 0x00000020u) {
      mutable_optional_value()->::onnx::OptionalProto::MergeFrom(from.optional_value());
    }
    if (cached_has_bits & 0x00000040u) {
      elem_type_ = from.elem_type_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void OptionalProto::CopyFrom(const OptionalProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:onnx.OptionalProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OptionalProto::IsInitialized() const {
  return true;
}

void OptionalProto::Swap(OptionalProto* other) {
  if (other == this) return;
  InternalSwap(other);
}
void OptionalProto::InternalSwap(OptionalProto* other) {
  using std::swap;
  name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(tensor_value_, other->tensor_value_);
  swap(sparse_tensor_value_, other->sparse_tensor_value_);
  swap(sequence_value_, other->sequence_value_);
  swap(map_value_, other->map_value_);
  swap(optional_value_, other->optional_value_);
  swap(elem_type_, other->elem_type_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string OptionalProto::GetTypeName() const {
  return "onnx.OptionalProto";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace onnx
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::onnx::SequenceProto* Arena::CreateMaybeMessage< ::onnx::SequenceProto >(Arena* arena) {
  return Arena::CreateInternal< ::onnx::SequenceProto >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::onnx::MapProto* Arena::CreateMaybeMessage< ::onnx::MapProto >(Arena* arena) {
  return Arena::CreateInternal< ::onnx::MapProto >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::onnx::OptionalProto* Arena::CreateMaybeMessage< ::onnx::OptionalProto >(Arena* arena) {
  return Arena::CreateInternal< ::onnx::OptionalProto >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
