NameSpace: muas

MessageProto:
  syntax = "proto3";
  package muas;
  message NDNSF_Request_Failure 
  {
    int32 code = 1;
    string msg = 2;
  }
  message ObjectDetection_YOLOv8_Request {
      bytes image_str = 1;
  }
  message ObjectDetection_YOLOv8_Response {
      repeated YOLOv8_DetectionResult results = 1;
  }
  message YOLOv8_DetectionResult {
    int32 classification = 1;
    float x_1 = 2;
    float y_1 = 3;
    float x_2 = 4;
    float y_2 = 5;
  }
  message FlightControl_Takeoff_Request
  {
    float latitude = 1;
    float longitude = 2;
  }
  message FlightControl_Takeoff_Response
  {
    float latitude = 1;
    float longitude = 2;
  }
  message FlightControl_Land_Request
  {
    float latitude = 1;
    float longitude = 2;
  }
  message FlightControl_Land_Response
  {
    float latitude = 1;
    float longitude = 2;
  }

  message FlightControl_ManualControl_Request
  {
    float x = 1;
    float y = 2;
    float z = 3;
    float r = 4;
    float s = 5;
    float t = 6;
  }
  message FlightControl_ManualControl_Response
  {
    float latitude = 1;
    float longitude = 2;
    float altitude = 3;
  }

Services:
- serviceName: ObjectDetection
  serviceDescription: Object Detection using YOLOv8
  RPCList:
  - name: YOLOv8
    requestMessage: muas::ObjectDetection_YOLOv8_Request
    responseMessage: muas::ObjectDetection_YOLOv8_Response
  - name: YOLOv8_S
    requestMessage: muas::ObjectDetection_YOLOv8_Request
    responseMessage: muas::ObjectDetection_YOLOv8_Response
- serviceName: FlightControl
  serviceDescription: FlightControl using MAVLINK
  RPCList:
  - name: Takeoff
    requestMessage: muas::FlightControl_Takeoff_Request
    responseMessage: muas::FlightControl_Takeoff_Response
  - name: Land
    requestMessage: muas::FlightControl_Land_Request
    responseMessage: muas::FlightControl_Land_Response
  - name: ManualControl
    requestMessage: muas::FlightControl_ManualControl_Request
    responseMessage: muas::FlightControl_ManualControl_Response

ServiceProviders:
- providerName: GS
  providerDescription: Ground Station of MUAS Project
  ServiceList:
  - ObjectDetection
- providerName: Drone
  providerDescription: Drone of MUAS Project
  ServiceList:
  - ObjectDetection
  - FlightControl

ServiceUsers:
- userName: GS
  userDescription: Ground Station of MUAS Project
  ServiceStubList:
  - ObjectDetection
  - FlightControl
- userName: Drone
  userDescription: Drone of MUAS Project
  ServiceStubList:
  - ObjectDetection


