// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

#ifndef PROTOBUF_INCLUDED_messages_2eproto
#define PROTOBUF_INCLUDED_messages_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_messages_2eproto 

namespace protobuf_messages_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[8];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_messages_2eproto
namespace muas {
class ManualControl_Land_Request;
class ManualControl_Land_RequestDefaultTypeInternal;
extern ManualControl_Land_RequestDefaultTypeInternal _ManualControl_Land_Request_default_instance_;
class ManualControl_Land_Response;
class ManualControl_Land_ResponseDefaultTypeInternal;
extern ManualControl_Land_ResponseDefaultTypeInternal _ManualControl_Land_Response_default_instance_;
class ManualControl_Takeoff_Request;
class ManualControl_Takeoff_RequestDefaultTypeInternal;
extern ManualControl_Takeoff_RequestDefaultTypeInternal _ManualControl_Takeoff_Request_default_instance_;
class ManualControl_Takeoff_Response;
class ManualControl_Takeoff_ResponseDefaultTypeInternal;
extern ManualControl_Takeoff_ResponseDefaultTypeInternal _ManualControl_Takeoff_Response_default_instance_;
class NDNSF_Request_Failure;
class NDNSF_Request_FailureDefaultTypeInternal;
extern NDNSF_Request_FailureDefaultTypeInternal _NDNSF_Request_Failure_default_instance_;
class ObjectDetection_YOLOv8_Request;
class ObjectDetection_YOLOv8_RequestDefaultTypeInternal;
extern ObjectDetection_YOLOv8_RequestDefaultTypeInternal _ObjectDetection_YOLOv8_Request_default_instance_;
class ObjectDetection_YOLOv8_Response;
class ObjectDetection_YOLOv8_ResponseDefaultTypeInternal;
extern ObjectDetection_YOLOv8_ResponseDefaultTypeInternal _ObjectDetection_YOLOv8_Response_default_instance_;
class YOLOv8_DetectionResult;
class YOLOv8_DetectionResultDefaultTypeInternal;
extern YOLOv8_DetectionResultDefaultTypeInternal _YOLOv8_DetectionResult_default_instance_;
}  // namespace muas
namespace google {
namespace protobuf {
template<> ::muas::ManualControl_Land_Request* Arena::CreateMaybeMessage<::muas::ManualControl_Land_Request>(Arena*);
template<> ::muas::ManualControl_Land_Response* Arena::CreateMaybeMessage<::muas::ManualControl_Land_Response>(Arena*);
template<> ::muas::ManualControl_Takeoff_Request* Arena::CreateMaybeMessage<::muas::ManualControl_Takeoff_Request>(Arena*);
template<> ::muas::ManualControl_Takeoff_Response* Arena::CreateMaybeMessage<::muas::ManualControl_Takeoff_Response>(Arena*);
template<> ::muas::NDNSF_Request_Failure* Arena::CreateMaybeMessage<::muas::NDNSF_Request_Failure>(Arena*);
template<> ::muas::ObjectDetection_YOLOv8_Request* Arena::CreateMaybeMessage<::muas::ObjectDetection_YOLOv8_Request>(Arena*);
template<> ::muas::ObjectDetection_YOLOv8_Response* Arena::CreateMaybeMessage<::muas::ObjectDetection_YOLOv8_Response>(Arena*);
template<> ::muas::YOLOv8_DetectionResult* Arena::CreateMaybeMessage<::muas::YOLOv8_DetectionResult>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace muas {

// ===================================================================

class NDNSF_Request_Failure : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:muas.NDNSF_Request_Failure) */ {
 public:
  NDNSF_Request_Failure();
  virtual ~NDNSF_Request_Failure();

  NDNSF_Request_Failure(const NDNSF_Request_Failure& from);

  inline NDNSF_Request_Failure& operator=(const NDNSF_Request_Failure& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  NDNSF_Request_Failure(NDNSF_Request_Failure&& from) noexcept
    : NDNSF_Request_Failure() {
    *this = ::std::move(from);
  }

  inline NDNSF_Request_Failure& operator=(NDNSF_Request_Failure&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const NDNSF_Request_Failure& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NDNSF_Request_Failure* internal_default_instance() {
    return reinterpret_cast<const NDNSF_Request_Failure*>(
               &_NDNSF_Request_Failure_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(NDNSF_Request_Failure* other);
  friend void swap(NDNSF_Request_Failure& a, NDNSF_Request_Failure& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline NDNSF_Request_Failure* New() const final {
    return CreateMaybeMessage<NDNSF_Request_Failure>(NULL);
  }

  NDNSF_Request_Failure* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<NDNSF_Request_Failure>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const NDNSF_Request_Failure& from);
  void MergeFrom(const NDNSF_Request_Failure& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NDNSF_Request_Failure* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string msg = 2;
  void clear_msg();
  static const int kMsgFieldNumber = 2;
  const ::std::string& msg() const;
  void set_msg(const ::std::string& value);
  #if LANG_CXX11
  void set_msg(::std::string&& value);
  #endif
  void set_msg(const char* value);
  void set_msg(const char* value, size_t size);
  ::std::string* mutable_msg();
  ::std::string* release_msg();
  void set_allocated_msg(::std::string* msg);

  // int32 code = 1;
  void clear_code();
  static const int kCodeFieldNumber = 1;
  ::google::protobuf::int32 code() const;
  void set_code(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:muas.NDNSF_Request_Failure)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr msg_;
  ::google::protobuf::int32 code_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_messages_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ObjectDetection_YOLOv8_Request : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:muas.ObjectDetection_YOLOv8_Request) */ {
 public:
  ObjectDetection_YOLOv8_Request();
  virtual ~ObjectDetection_YOLOv8_Request();

  ObjectDetection_YOLOv8_Request(const ObjectDetection_YOLOv8_Request& from);

  inline ObjectDetection_YOLOv8_Request& operator=(const ObjectDetection_YOLOv8_Request& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ObjectDetection_YOLOv8_Request(ObjectDetection_YOLOv8_Request&& from) noexcept
    : ObjectDetection_YOLOv8_Request() {
    *this = ::std::move(from);
  }

  inline ObjectDetection_YOLOv8_Request& operator=(ObjectDetection_YOLOv8_Request&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ObjectDetection_YOLOv8_Request& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ObjectDetection_YOLOv8_Request* internal_default_instance() {
    return reinterpret_cast<const ObjectDetection_YOLOv8_Request*>(
               &_ObjectDetection_YOLOv8_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ObjectDetection_YOLOv8_Request* other);
  friend void swap(ObjectDetection_YOLOv8_Request& a, ObjectDetection_YOLOv8_Request& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ObjectDetection_YOLOv8_Request* New() const final {
    return CreateMaybeMessage<ObjectDetection_YOLOv8_Request>(NULL);
  }

  ObjectDetection_YOLOv8_Request* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ObjectDetection_YOLOv8_Request>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ObjectDetection_YOLOv8_Request& from);
  void MergeFrom(const ObjectDetection_YOLOv8_Request& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ObjectDetection_YOLOv8_Request* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes image_str = 1;
  void clear_image_str();
  static const int kImageStrFieldNumber = 1;
  const ::std::string& image_str() const;
  void set_image_str(const ::std::string& value);
  #if LANG_CXX11
  void set_image_str(::std::string&& value);
  #endif
  void set_image_str(const char* value);
  void set_image_str(const void* value, size_t size);
  ::std::string* mutable_image_str();
  ::std::string* release_image_str();
  void set_allocated_image_str(::std::string* image_str);

  // @@protoc_insertion_point(class_scope:muas.ObjectDetection_YOLOv8_Request)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr image_str_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_messages_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ObjectDetection_YOLOv8_Response : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:muas.ObjectDetection_YOLOv8_Response) */ {
 public:
  ObjectDetection_YOLOv8_Response();
  virtual ~ObjectDetection_YOLOv8_Response();

  ObjectDetection_YOLOv8_Response(const ObjectDetection_YOLOv8_Response& from);

  inline ObjectDetection_YOLOv8_Response& operator=(const ObjectDetection_YOLOv8_Response& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ObjectDetection_YOLOv8_Response(ObjectDetection_YOLOv8_Response&& from) noexcept
    : ObjectDetection_YOLOv8_Response() {
    *this = ::std::move(from);
  }

  inline ObjectDetection_YOLOv8_Response& operator=(ObjectDetection_YOLOv8_Response&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ObjectDetection_YOLOv8_Response& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ObjectDetection_YOLOv8_Response* internal_default_instance() {
    return reinterpret_cast<const ObjectDetection_YOLOv8_Response*>(
               &_ObjectDetection_YOLOv8_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(ObjectDetection_YOLOv8_Response* other);
  friend void swap(ObjectDetection_YOLOv8_Response& a, ObjectDetection_YOLOv8_Response& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ObjectDetection_YOLOv8_Response* New() const final {
    return CreateMaybeMessage<ObjectDetection_YOLOv8_Response>(NULL);
  }

  ObjectDetection_YOLOv8_Response* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ObjectDetection_YOLOv8_Response>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ObjectDetection_YOLOv8_Response& from);
  void MergeFrom(const ObjectDetection_YOLOv8_Response& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ObjectDetection_YOLOv8_Response* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .muas.YOLOv8_DetectionResult results = 1;
  int results_size() const;
  void clear_results();
  static const int kResultsFieldNumber = 1;
  ::muas::YOLOv8_DetectionResult* mutable_results(int index);
  ::google::protobuf::RepeatedPtrField< ::muas::YOLOv8_DetectionResult >*
      mutable_results();
  const ::muas::YOLOv8_DetectionResult& results(int index) const;
  ::muas::YOLOv8_DetectionResult* add_results();
  const ::google::protobuf::RepeatedPtrField< ::muas::YOLOv8_DetectionResult >&
      results() const;

  // @@protoc_insertion_point(class_scope:muas.ObjectDetection_YOLOv8_Response)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::muas::YOLOv8_DetectionResult > results_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_messages_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class YOLOv8_DetectionResult : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:muas.YOLOv8_DetectionResult) */ {
 public:
  YOLOv8_DetectionResult();
  virtual ~YOLOv8_DetectionResult();

  YOLOv8_DetectionResult(const YOLOv8_DetectionResult& from);

  inline YOLOv8_DetectionResult& operator=(const YOLOv8_DetectionResult& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  YOLOv8_DetectionResult(YOLOv8_DetectionResult&& from) noexcept
    : YOLOv8_DetectionResult() {
    *this = ::std::move(from);
  }

  inline YOLOv8_DetectionResult& operator=(YOLOv8_DetectionResult&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const YOLOv8_DetectionResult& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const YOLOv8_DetectionResult* internal_default_instance() {
    return reinterpret_cast<const YOLOv8_DetectionResult*>(
               &_YOLOv8_DetectionResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(YOLOv8_DetectionResult* other);
  friend void swap(YOLOv8_DetectionResult& a, YOLOv8_DetectionResult& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline YOLOv8_DetectionResult* New() const final {
    return CreateMaybeMessage<YOLOv8_DetectionResult>(NULL);
  }

  YOLOv8_DetectionResult* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<YOLOv8_DetectionResult>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const YOLOv8_DetectionResult& from);
  void MergeFrom(const YOLOv8_DetectionResult& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(YOLOv8_DetectionResult* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 classification = 1;
  void clear_classification();
  static const int kClassificationFieldNumber = 1;
  ::google::protobuf::int32 classification() const;
  void set_classification(::google::protobuf::int32 value);

  // float x_1 = 2;
  void clear_x_1();
  static const int kX1FieldNumber = 2;
  float x_1() const;
  void set_x_1(float value);

  // float y_1 = 3;
  void clear_y_1();
  static const int kY1FieldNumber = 3;
  float y_1() const;
  void set_y_1(float value);

  // float x_2 = 4;
  void clear_x_2();
  static const int kX2FieldNumber = 4;
  float x_2() const;
  void set_x_2(float value);

  // float y_2 = 5;
  void clear_y_2();
  static const int kY2FieldNumber = 5;
  float y_2() const;
  void set_y_2(float value);

  // @@protoc_insertion_point(class_scope:muas.YOLOv8_DetectionResult)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 classification_;
  float x_1_;
  float y_1_;
  float x_2_;
  float y_2_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_messages_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ManualControl_Takeoff_Request : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:muas.ManualControl_Takeoff_Request) */ {
 public:
  ManualControl_Takeoff_Request();
  virtual ~ManualControl_Takeoff_Request();

  ManualControl_Takeoff_Request(const ManualControl_Takeoff_Request& from);

  inline ManualControl_Takeoff_Request& operator=(const ManualControl_Takeoff_Request& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ManualControl_Takeoff_Request(ManualControl_Takeoff_Request&& from) noexcept
    : ManualControl_Takeoff_Request() {
    *this = ::std::move(from);
  }

  inline ManualControl_Takeoff_Request& operator=(ManualControl_Takeoff_Request&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ManualControl_Takeoff_Request& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ManualControl_Takeoff_Request* internal_default_instance() {
    return reinterpret_cast<const ManualControl_Takeoff_Request*>(
               &_ManualControl_Takeoff_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(ManualControl_Takeoff_Request* other);
  friend void swap(ManualControl_Takeoff_Request& a, ManualControl_Takeoff_Request& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ManualControl_Takeoff_Request* New() const final {
    return CreateMaybeMessage<ManualControl_Takeoff_Request>(NULL);
  }

  ManualControl_Takeoff_Request* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ManualControl_Takeoff_Request>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ManualControl_Takeoff_Request& from);
  void MergeFrom(const ManualControl_Takeoff_Request& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ManualControl_Takeoff_Request* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // float latitude = 1;
  void clear_latitude();
  static const int kLatitudeFieldNumber = 1;
  float latitude() const;
  void set_latitude(float value);

  // float longitude = 2;
  void clear_longitude();
  static const int kLongitudeFieldNumber = 2;
  float longitude() const;
  void set_longitude(float value);

  // @@protoc_insertion_point(class_scope:muas.ManualControl_Takeoff_Request)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  float latitude_;
  float longitude_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_messages_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ManualControl_Takeoff_Response : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:muas.ManualControl_Takeoff_Response) */ {
 public:
  ManualControl_Takeoff_Response();
  virtual ~ManualControl_Takeoff_Response();

  ManualControl_Takeoff_Response(const ManualControl_Takeoff_Response& from);

  inline ManualControl_Takeoff_Response& operator=(const ManualControl_Takeoff_Response& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ManualControl_Takeoff_Response(ManualControl_Takeoff_Response&& from) noexcept
    : ManualControl_Takeoff_Response() {
    *this = ::std::move(from);
  }

  inline ManualControl_Takeoff_Response& operator=(ManualControl_Takeoff_Response&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ManualControl_Takeoff_Response& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ManualControl_Takeoff_Response* internal_default_instance() {
    return reinterpret_cast<const ManualControl_Takeoff_Response*>(
               &_ManualControl_Takeoff_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(ManualControl_Takeoff_Response* other);
  friend void swap(ManualControl_Takeoff_Response& a, ManualControl_Takeoff_Response& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ManualControl_Takeoff_Response* New() const final {
    return CreateMaybeMessage<ManualControl_Takeoff_Response>(NULL);
  }

  ManualControl_Takeoff_Response* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ManualControl_Takeoff_Response>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ManualControl_Takeoff_Response& from);
  void MergeFrom(const ManualControl_Takeoff_Response& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ManualControl_Takeoff_Response* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // float latitude = 1;
  void clear_latitude();
  static const int kLatitudeFieldNumber = 1;
  float latitude() const;
  void set_latitude(float value);

  // float longitude = 2;
  void clear_longitude();
  static const int kLongitudeFieldNumber = 2;
  float longitude() const;
  void set_longitude(float value);

  // @@protoc_insertion_point(class_scope:muas.ManualControl_Takeoff_Response)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  float latitude_;
  float longitude_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_messages_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ManualControl_Land_Request : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:muas.ManualControl_Land_Request) */ {
 public:
  ManualControl_Land_Request();
  virtual ~ManualControl_Land_Request();

  ManualControl_Land_Request(const ManualControl_Land_Request& from);

  inline ManualControl_Land_Request& operator=(const ManualControl_Land_Request& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ManualControl_Land_Request(ManualControl_Land_Request&& from) noexcept
    : ManualControl_Land_Request() {
    *this = ::std::move(from);
  }

  inline ManualControl_Land_Request& operator=(ManualControl_Land_Request&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ManualControl_Land_Request& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ManualControl_Land_Request* internal_default_instance() {
    return reinterpret_cast<const ManualControl_Land_Request*>(
               &_ManualControl_Land_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(ManualControl_Land_Request* other);
  friend void swap(ManualControl_Land_Request& a, ManualControl_Land_Request& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ManualControl_Land_Request* New() const final {
    return CreateMaybeMessage<ManualControl_Land_Request>(NULL);
  }

  ManualControl_Land_Request* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ManualControl_Land_Request>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ManualControl_Land_Request& from);
  void MergeFrom(const ManualControl_Land_Request& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ManualControl_Land_Request* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // float latitude = 1;
  void clear_latitude();
  static const int kLatitudeFieldNumber = 1;
  float latitude() const;
  void set_latitude(float value);

  // float longitude = 2;
  void clear_longitude();
  static const int kLongitudeFieldNumber = 2;
  float longitude() const;
  void set_longitude(float value);

  // @@protoc_insertion_point(class_scope:muas.ManualControl_Land_Request)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  float latitude_;
  float longitude_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_messages_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ManualControl_Land_Response : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:muas.ManualControl_Land_Response) */ {
 public:
  ManualControl_Land_Response();
  virtual ~ManualControl_Land_Response();

  ManualControl_Land_Response(const ManualControl_Land_Response& from);

  inline ManualControl_Land_Response& operator=(const ManualControl_Land_Response& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ManualControl_Land_Response(ManualControl_Land_Response&& from) noexcept
    : ManualControl_Land_Response() {
    *this = ::std::move(from);
  }

  inline ManualControl_Land_Response& operator=(ManualControl_Land_Response&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ManualControl_Land_Response& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ManualControl_Land_Response* internal_default_instance() {
    return reinterpret_cast<const ManualControl_Land_Response*>(
               &_ManualControl_Land_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  void Swap(ManualControl_Land_Response* other);
  friend void swap(ManualControl_Land_Response& a, ManualControl_Land_Response& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ManualControl_Land_Response* New() const final {
    return CreateMaybeMessage<ManualControl_Land_Response>(NULL);
  }

  ManualControl_Land_Response* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ManualControl_Land_Response>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ManualControl_Land_Response& from);
  void MergeFrom(const ManualControl_Land_Response& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ManualControl_Land_Response* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // float latitude = 1;
  void clear_latitude();
  static const int kLatitudeFieldNumber = 1;
  float latitude() const;
  void set_latitude(float value);

  // float longitude = 2;
  void clear_longitude();
  static const int kLongitudeFieldNumber = 2;
  float longitude() const;
  void set_longitude(float value);

  // @@protoc_insertion_point(class_scope:muas.ManualControl_Land_Response)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  float latitude_;
  float longitude_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_messages_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// NDNSF_Request_Failure

// int32 code = 1;
inline void NDNSF_Request_Failure::clear_code() {
  code_ = 0;
}
inline ::google::protobuf::int32 NDNSF_Request_Failure::code() const {
  // @@protoc_insertion_point(field_get:muas.NDNSF_Request_Failure.code)
  return code_;
}
inline void NDNSF_Request_Failure::set_code(::google::protobuf::int32 value) {
  
  code_ = value;
  // @@protoc_insertion_point(field_set:muas.NDNSF_Request_Failure.code)
}

// string msg = 2;
inline void NDNSF_Request_Failure::clear_msg() {
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& NDNSF_Request_Failure::msg() const {
  // @@protoc_insertion_point(field_get:muas.NDNSF_Request_Failure.msg)
  return msg_.GetNoArena();
}
inline void NDNSF_Request_Failure::set_msg(const ::std::string& value) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:muas.NDNSF_Request_Failure.msg)
}
#if LANG_CXX11
inline void NDNSF_Request_Failure::set_msg(::std::string&& value) {
  
  msg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:muas.NDNSF_Request_Failure.msg)
}
#endif
inline void NDNSF_Request_Failure::set_msg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:muas.NDNSF_Request_Failure.msg)
}
inline void NDNSF_Request_Failure::set_msg(const char* value, size_t size) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:muas.NDNSF_Request_Failure.msg)
}
inline ::std::string* NDNSF_Request_Failure::mutable_msg() {
  
  // @@protoc_insertion_point(field_mutable:muas.NDNSF_Request_Failure.msg)
  return msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NDNSF_Request_Failure::release_msg() {
  // @@protoc_insertion_point(field_release:muas.NDNSF_Request_Failure.msg)
  
  return msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NDNSF_Request_Failure::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    
  } else {
    
  }
  msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:muas.NDNSF_Request_Failure.msg)
}

// -------------------------------------------------------------------

// ObjectDetection_YOLOv8_Request

// bytes image_str = 1;
inline void ObjectDetection_YOLOv8_Request::clear_image_str() {
  image_str_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ObjectDetection_YOLOv8_Request::image_str() const {
  // @@protoc_insertion_point(field_get:muas.ObjectDetection_YOLOv8_Request.image_str)
  return image_str_.GetNoArena();
}
inline void ObjectDetection_YOLOv8_Request::set_image_str(const ::std::string& value) {
  
  image_str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:muas.ObjectDetection_YOLOv8_Request.image_str)
}
#if LANG_CXX11
inline void ObjectDetection_YOLOv8_Request::set_image_str(::std::string&& value) {
  
  image_str_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:muas.ObjectDetection_YOLOv8_Request.image_str)
}
#endif
inline void ObjectDetection_YOLOv8_Request::set_image_str(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  image_str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:muas.ObjectDetection_YOLOv8_Request.image_str)
}
inline void ObjectDetection_YOLOv8_Request::set_image_str(const void* value, size_t size) {
  
  image_str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:muas.ObjectDetection_YOLOv8_Request.image_str)
}
inline ::std::string* ObjectDetection_YOLOv8_Request::mutable_image_str() {
  
  // @@protoc_insertion_point(field_mutable:muas.ObjectDetection_YOLOv8_Request.image_str)
  return image_str_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ObjectDetection_YOLOv8_Request::release_image_str() {
  // @@protoc_insertion_point(field_release:muas.ObjectDetection_YOLOv8_Request.image_str)
  
  return image_str_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ObjectDetection_YOLOv8_Request::set_allocated_image_str(::std::string* image_str) {
  if (image_str != NULL) {
    
  } else {
    
  }
  image_str_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), image_str);
  // @@protoc_insertion_point(field_set_allocated:muas.ObjectDetection_YOLOv8_Request.image_str)
}

// -------------------------------------------------------------------

// ObjectDetection_YOLOv8_Response

// repeated .muas.YOLOv8_DetectionResult results = 1;
inline int ObjectDetection_YOLOv8_Response::results_size() const {
  return results_.size();
}
inline void ObjectDetection_YOLOv8_Response::clear_results() {
  results_.Clear();
}
inline ::muas::YOLOv8_DetectionResult* ObjectDetection_YOLOv8_Response::mutable_results(int index) {
  // @@protoc_insertion_point(field_mutable:muas.ObjectDetection_YOLOv8_Response.results)
  return results_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::muas::YOLOv8_DetectionResult >*
ObjectDetection_YOLOv8_Response::mutable_results() {
  // @@protoc_insertion_point(field_mutable_list:muas.ObjectDetection_YOLOv8_Response.results)
  return &results_;
}
inline const ::muas::YOLOv8_DetectionResult& ObjectDetection_YOLOv8_Response::results(int index) const {
  // @@protoc_insertion_point(field_get:muas.ObjectDetection_YOLOv8_Response.results)
  return results_.Get(index);
}
inline ::muas::YOLOv8_DetectionResult* ObjectDetection_YOLOv8_Response::add_results() {
  // @@protoc_insertion_point(field_add:muas.ObjectDetection_YOLOv8_Response.results)
  return results_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::muas::YOLOv8_DetectionResult >&
ObjectDetection_YOLOv8_Response::results() const {
  // @@protoc_insertion_point(field_list:muas.ObjectDetection_YOLOv8_Response.results)
  return results_;
}

// -------------------------------------------------------------------

// YOLOv8_DetectionResult

// int32 classification = 1;
inline void YOLOv8_DetectionResult::clear_classification() {
  classification_ = 0;
}
inline ::google::protobuf::int32 YOLOv8_DetectionResult::classification() const {
  // @@protoc_insertion_point(field_get:muas.YOLOv8_DetectionResult.classification)
  return classification_;
}
inline void YOLOv8_DetectionResult::set_classification(::google::protobuf::int32 value) {
  
  classification_ = value;
  // @@protoc_insertion_point(field_set:muas.YOLOv8_DetectionResult.classification)
}

// float x_1 = 2;
inline void YOLOv8_DetectionResult::clear_x_1() {
  x_1_ = 0;
}
inline float YOLOv8_DetectionResult::x_1() const {
  // @@protoc_insertion_point(field_get:muas.YOLOv8_DetectionResult.x_1)
  return x_1_;
}
inline void YOLOv8_DetectionResult::set_x_1(float value) {
  
  x_1_ = value;
  // @@protoc_insertion_point(field_set:muas.YOLOv8_DetectionResult.x_1)
}

// float y_1 = 3;
inline void YOLOv8_DetectionResult::clear_y_1() {
  y_1_ = 0;
}
inline float YOLOv8_DetectionResult::y_1() const {
  // @@protoc_insertion_point(field_get:muas.YOLOv8_DetectionResult.y_1)
  return y_1_;
}
inline void YOLOv8_DetectionResult::set_y_1(float value) {
  
  y_1_ = value;
  // @@protoc_insertion_point(field_set:muas.YOLOv8_DetectionResult.y_1)
}

// float x_2 = 4;
inline void YOLOv8_DetectionResult::clear_x_2() {
  x_2_ = 0;
}
inline float YOLOv8_DetectionResult::x_2() const {
  // @@protoc_insertion_point(field_get:muas.YOLOv8_DetectionResult.x_2)
  return x_2_;
}
inline void YOLOv8_DetectionResult::set_x_2(float value) {
  
  x_2_ = value;
  // @@protoc_insertion_point(field_set:muas.YOLOv8_DetectionResult.x_2)
}

// float y_2 = 5;
inline void YOLOv8_DetectionResult::clear_y_2() {
  y_2_ = 0;
}
inline float YOLOv8_DetectionResult::y_2() const {
  // @@protoc_insertion_point(field_get:muas.YOLOv8_DetectionResult.y_2)
  return y_2_;
}
inline void YOLOv8_DetectionResult::set_y_2(float value) {
  
  y_2_ = value;
  // @@protoc_insertion_point(field_set:muas.YOLOv8_DetectionResult.y_2)
}

// -------------------------------------------------------------------

// ManualControl_Takeoff_Request

// float latitude = 1;
inline void ManualControl_Takeoff_Request::clear_latitude() {
  latitude_ = 0;
}
inline float ManualControl_Takeoff_Request::latitude() const {
  // @@protoc_insertion_point(field_get:muas.ManualControl_Takeoff_Request.latitude)
  return latitude_;
}
inline void ManualControl_Takeoff_Request::set_latitude(float value) {
  
  latitude_ = value;
  // @@protoc_insertion_point(field_set:muas.ManualControl_Takeoff_Request.latitude)
}

// float longitude = 2;
inline void ManualControl_Takeoff_Request::clear_longitude() {
  longitude_ = 0;
}
inline float ManualControl_Takeoff_Request::longitude() const {
  // @@protoc_insertion_point(field_get:muas.ManualControl_Takeoff_Request.longitude)
  return longitude_;
}
inline void ManualControl_Takeoff_Request::set_longitude(float value) {
  
  longitude_ = value;
  // @@protoc_insertion_point(field_set:muas.ManualControl_Takeoff_Request.longitude)
}

// -------------------------------------------------------------------

// ManualControl_Takeoff_Response

// float latitude = 1;
inline void ManualControl_Takeoff_Response::clear_latitude() {
  latitude_ = 0;
}
inline float ManualControl_Takeoff_Response::latitude() const {
  // @@protoc_insertion_point(field_get:muas.ManualControl_Takeoff_Response.latitude)
  return latitude_;
}
inline void ManualControl_Takeoff_Response::set_latitude(float value) {
  
  latitude_ = value;
  // @@protoc_insertion_point(field_set:muas.ManualControl_Takeoff_Response.latitude)
}

// float longitude = 2;
inline void ManualControl_Takeoff_Response::clear_longitude() {
  longitude_ = 0;
}
inline float ManualControl_Takeoff_Response::longitude() const {
  // @@protoc_insertion_point(field_get:muas.ManualControl_Takeoff_Response.longitude)
  return longitude_;
}
inline void ManualControl_Takeoff_Response::set_longitude(float value) {
  
  longitude_ = value;
  // @@protoc_insertion_point(field_set:muas.ManualControl_Takeoff_Response.longitude)
}

// -------------------------------------------------------------------

// ManualControl_Land_Request

// float latitude = 1;
inline void ManualControl_Land_Request::clear_latitude() {
  latitude_ = 0;
}
inline float ManualControl_Land_Request::latitude() const {
  // @@protoc_insertion_point(field_get:muas.ManualControl_Land_Request.latitude)
  return latitude_;
}
inline void ManualControl_Land_Request::set_latitude(float value) {
  
  latitude_ = value;
  // @@protoc_insertion_point(field_set:muas.ManualControl_Land_Request.latitude)
}

// float longitude = 2;
inline void ManualControl_Land_Request::clear_longitude() {
  longitude_ = 0;
}
inline float ManualControl_Land_Request::longitude() const {
  // @@protoc_insertion_point(field_get:muas.ManualControl_Land_Request.longitude)
  return longitude_;
}
inline void ManualControl_Land_Request::set_longitude(float value) {
  
  longitude_ = value;
  // @@protoc_insertion_point(field_set:muas.ManualControl_Land_Request.longitude)
}

// -------------------------------------------------------------------

// ManualControl_Land_Response

// float latitude = 1;
inline void ManualControl_Land_Response::clear_latitude() {
  latitude_ = 0;
}
inline float ManualControl_Land_Response::latitude() const {
  // @@protoc_insertion_point(field_get:muas.ManualControl_Land_Response.latitude)
  return latitude_;
}
inline void ManualControl_Land_Response::set_latitude(float value) {
  
  latitude_ = value;
  // @@protoc_insertion_point(field_set:muas.ManualControl_Land_Response.latitude)
}

// float longitude = 2;
inline void ManualControl_Land_Response::clear_longitude() {
  longitude_ = 0;
}
inline float ManualControl_Land_Response::longitude() const {
  // @@protoc_insertion_point(field_get:muas.ManualControl_Land_Response.longitude)
  return longitude_;
}
inline void ManualControl_Land_Response::set_longitude(float value) {
  
  longitude_ = value;
  // @@protoc_insertion_point(field_set:muas.ManualControl_Land_Response.longitude)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace muas

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_messages_2eproto
