---
openapi-ndn : 0.0.1

info:
  title: OpenAPI 3.0 for NDN
  description: An experiment to customize OpenAPI 3.0 for Named Data Network
  
app:
  - app_name : /muas
  - appVersion : 0.0.1
  - sync_protocol : ndn-svs
  - status_code:
      "200" : "ok"
      "400" : "Bad Request: Mismatch between Reuquest Data and Service"
      "401" : "Unauthorized"
      "404" : "Service Not Found"
      "500" : "internal server error"

global_security:
  validation : true
  trust_anchor : []
  trusted_certificate: []
  trusted_certificate_folder: []

services:
  /object_detection/yolov8:
    request: "muas::ObjectDetectionServiceRequestMessage"
    response: "muas::ObjectDetectionServiceResponseMessage"
    security:
      api_key: []


