top = '..'

def build(bld):
    bld.program(name='App_ServiceController',
                target='App_ServiceController',
                source=['App_ServiceController.cpp'],
                includes=['..'],
                use='ndn-service-framework NDN_CXX NDN_SVS BOOST NAC-ABE NDNSD',
                linkflags=['-Wl,-rpath,$ORIGIN/..'],
                install_path=None)

    bld.program(name='App_Provider',
                target='App_Provider',
                source=['App_Provider.cpp'],
                includes=['..'],
                use='ndn-service-framework NDN_CXX NDN_SVS BOOST NAC-ABE NDNSD',
                linkflags=['-Wl,-rpath,$ORIGIN/..'],
                install_path=None)

    bld.program(name='App_User',
                target='App_User',
                source=['App_User.cpp'],
                includes=['..'],
                use='ndn-service-framework NDN_CXX NDN_SVS BOOST NAC-ABE NDNSD',
                linkflags=['-Wl,-rpath,$ORIGIN/..'],
                install_path=None)

    bld.program(name='App_SvsLatency',
                target='App_SvsLatency',
                source=['App_SvsLatency.cpp'],
                includes=['..'],
                use='NDN_CXX NDN_SVS BOOST',
                linkflags=['-Wl,-rpath,$ORIGIN/..'],
                install_path=None)

    bld.program(name='App_IntermittentProvider',
                target='App_IntermittentProvider',
                source=['App_IntermittentProvider.cpp'],
                includes=['..'],
                use='ndn-service-framework NDN_CXX NDN_SVS BOOST NAC-ABE NDNSD',
                linkflags=['-Wl,-rpath,$ORIGIN/..'],
                install_path=None)

    bld.program(name='App_IntermittentUser',
                target='App_IntermittentUser',
                source=['App_IntermittentUser.cpp'],
                includes=['..'],
                use='ndn-service-framework NDN_CXX NDN_SVS BOOST NAC-ABE NDNSD',
                linkflags=['-Wl,-rpath,$ORIGIN/..'],
                install_path=None)

    bld.program(name='AI_DistributedCollaborationProvider',
                target='AI_DistributedCollaborationProvider',
                source=['AI_DistributedCollaborationProvider.cpp'],
                includes=['..'],
                use='ndn-service-framework NDN_CXX NDN_SVS BOOST NAC-ABE NDNSD',
                linkflags=['-Wl,-rpath,$ORIGIN/..'],
                install_path=None)

    bld.program(name='AI_User',
                target='AI_User',
                source=['AI_User.cpp'],
                includes=['..'],
                use='ndn-service-framework NDN_CXX NDN_SVS BOOST NAC-ABE NDNSD',
                linkflags=['-Wl,-rpath,$ORIGIN/..'],
                install_path=None)

    bld.program(name='Payment_CollaborationProvider',
                target='Payment_CollaborationProvider',
                source=['Payment_CollaborationProvider.cpp'],
                includes=['..'],
                use='ndn-service-framework NDN_CXX NDN_SVS BOOST NAC-ABE NDNSD',
                linkflags=['-Wl,-rpath,$ORIGIN/..'],
                install_path=None)

    bld.program(name='Payment_User',
                target='Payment_User',
                source=['Payment_User.cpp'],
                includes=['..'],
                use='ndn-service-framework NDN_CXX NDN_SVS BOOST NAC-ABE NDNSD',
                linkflags=['-Wl,-rpath,$ORIGIN/..'],
                install_path=None)

    bld.program(name='UavDroneApp',
                target='UavDroneApp',
                source=[
                    '../NDNSF-UAV-APP/drone/UavDroneApp.cpp',
                    '../NDNSF-UAV-APP/shared/UavProtocol.cpp',
                ],
                includes=['..', '../NDNSF-UAV-APP/shared', '../NDNSF-DistributedRepo/include'],
                use='ndnsf-distributed-repo ndn-service-framework NDN_CXX NDN_SVS BOOST NAC-ABE NDNSD gtkmm sqlite3',
                cxxflags=['-Wno-error=extra-semi'],
                linkflags=['-Wl,-rpath,$ORIGIN/..'],
                install_path=None)

    bld.program(name='UavGroundStationApp',
                target='UavGroundStationApp',
                source=[
                    '../NDNSF-UAV-APP/ground-station/UavGroundStationApp.cpp',
                    '../NDNSF-UAV-APP/shared/UavProtocol.cpp',
                ],
                includes=['..', '../NDNSF-UAV-APP/shared'],
                use='ndn-service-framework NDN_CXX NDN_SVS BOOST NAC-ABE NDNSD gtkmm',
                cxxflags=['-Wno-error=extra-semi'],
                linkflags=['-Wl,-rpath,$ORIGIN/..'],
                install_path=None)

    bld.program(name='App_WifiMobilityProvider',
                target='App_WifiMobilityProvider',
                source=['App_IntermittentProvider.cpp'],
                includes=['..'],
                use='ndn-service-framework NDN_CXX NDN_SVS BOOST NAC-ABE NDNSD',
                linkflags=['-Wl,-rpath,$ORIGIN/..'],
                install_path=None)

    bld.program(name='App_WifiMobilityUser',
                target='App_WifiMobilityUser',
                source=['App_IntermittentUser.cpp'],
                includes=['..'],
                use='ndn-service-framework NDN_CXX NDN_SVS BOOST NAC-ABE NDNSD',
                linkflags=['-Wl,-rpath,$ORIGIN/..'],
                install_path=None)

    if not bld.env.WITH_EXAMPLES:
        return

    bld.program(name='generic-dynamic-user-provider',
                target='generic-dynamic-user-provider',
                source=(["generic-dynamic-user-provider.cpp"] +
                        bld.path.parent.ant_glob([
                            'ndn-service-framework/NDNSFMessages.cpp',
                            'ndn-service-framework/BloomFilter.cpp',
                            'ndn-service-framework/ConfigManager.cpp',
                            'ndn-service-framework/Service.cpp',
                            'ndn-service-framework/ServiceProvider.cpp',
                            'ndn-service-framework/ServiceUser.cpp',
                            'ndn-service-framework/HybridMessageCrypto.cpp',
                            'ndn-service-framework/TimelineTrace.cpp',
                            'ndn-service-framework/common.cpp',
                            'ndn-service-framework/utils.cpp',
                        ])),
                includes= ['..','../ndn-service-framework'],
                use='NDN_CXX NDN_SVS PROTOBUF NAC-ABE NDNSD OPENSSL',
                cxxflags=['-fPIC'],
                install_path=None)

    bld.install_files('/usr/local/bin', ['trust-schema.conf', 'trust-any.conf', 'example_muas.policies'])
