d /run/ndnsf-di 0750 ndnsf-di ndnsf-di -
d /var/lib/ndnsf-di 0750 ndnsf-di ndnsf-di -
d /var/lib/ndnsf-di/cache 0750 ndnsf-di ndnsf-di -
d /var/lib/ndnsf-di/results 0750 ndnsf-di ndnsf-di -
d /var/lib/ndnsf-repo 0750 ndnsf-di-repo ndnsf-di-repo -
d /var/log/ndnsf-di 0750 ndnsf-di ndnsf-di -
