[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
[project]
name = "ndnsf-di-sdk"
version = "0.111.0"
dependencies = ["ndnsf-di-core==0.111.0"]
[tool.setuptools]
package-dir = {"" = "../../.."}
packages = [
  "ndnsf_distributed_inference.sdk",
  "ndnsf_distributed_inference.adapters",
]
