#include "tests/boost-test.hpp"

#include "NDNSF-DistributedInference/cpp/ndnsf-di/NativeGrantVerifier.hpp"

#include <boost/property_tree/json_parser.hpp>
#include <boost/property_tree/ptree.hpp>

#include <fstream>
#include <sstream>
#include <stdexcept>

// spec181 T002/T003: the native verifier must unwrap the SAME fixed grant
// byte stream as the Python verifier (cross-language parity vectors,
// tests/fixtures/spec181/grant-vectors-v1.json).  The vector file is
// generated by scripts/gen_spec181_grant_vectors.py and locked by T003.

namespace ndnsf::di::test {
namespace {

struct VectorCase
{
  std::string name;
  std::string wire;
  bool expectedOk = false;
  std::string expectedContentKey;
  std::string expectedReason;
  std::string requestId;
  std::uint64_t attempt = 0;
  std::string planCoreDigest;
  std::string modelManifestDigest;
  std::string protectionEpoch;
  std::uint64_t nowMs = 0;
};

std::string
readTextFile(const std::string& path)
{
  std::ifstream input(path);
  if (!input) {
    throw std::runtime_error("cannot open fixture: " + path);
  }
  std::ostringstream buffer;
  buffer << input.rdbuf();
  return buffer.str();
}

boost::property_tree::ptree
loadVectors()
{
  std::string text;
  // The unit-tests binary runs from the waf build directory
  // (build-system-j2), whose parent is the repository root.
  const char* candidates[] = {
    "tests/fixtures/spec181/grant-vectors-v1.json",
    "../tests/fixtures/spec181/grant-vectors-v1.json",
  };
  for (const auto* candidate : candidates) {
    std::ifstream input(candidate);
    if (!input) {
      continue;
    }
    std::ostringstream buffer;
    buffer << input.rdbuf();
    text = buffer.str();
    break;
  }
  if (text.empty()) {
    throw std::runtime_error(
      "grant vector fixture not found; run from the repository root or the "
      "waf build directory");
  }
  boost::property_tree::ptree root;
  std::istringstream input(text);
  boost::property_tree::read_json(input, root);
  return root;
}

VectorCase
caseFrom(const boost::property_tree::ptree& node,
         const boost::property_tree::ptree& root)
{
  VectorCase value;
  value.name = node.get<std::string>("name");
  value.wire = node.get<std::string>("wire");
  value.expectedOk = node.get<bool>("expected.ok", false);
  value.expectedContentKey = node.get<std::string>("expected.contentKey", "");
  value.expectedReason = node.get<std::string>("expected.reason", "");
  value.requestId = node.get<std::string>("binding.requestId",
    root.get<std::string>("requestId"));
  value.attempt = node.get<std::uint64_t>("binding.attempt",
    root.get<std::uint64_t>("attempt"));
  value.planCoreDigest = node.get<std::string>("binding.planCoreDigest",
    root.get<std::string>("planCoreDigest"));
  value.modelManifestDigest =
    node.get<std::string>("binding.modelManifestDigest",
      root.get<std::string>("modelManifestDigest"));
  value.protectionEpoch = node.get<std::string>("binding.protectionEpoch",
    root.get<std::string>("protectionEpoch"));
  value.nowMs = node.get<std::uint64_t>("binding.nowMs",
    root.get<std::uint64_t>("nowMs") + 1000);
  return value;
}

} // namespace

BOOST_AUTO_TEST_CASE(NativeGrantVerifierMatchesPythonParityVectors)
{
  const auto root = loadVectors();
  const auto authorityPublicKeyRaw =
    root.get<std::string>("authorityPublicKeyRaw");
  const auto recipientSeed = root.get<std::string>("recipientSeed");
  const auto providerIdentity = root.get<std::string>("providerIdentity");
  const auto requestId = root.get<std::string>("requestId");
  const auto attempt = root.get<std::uint64_t>("attempt");
  const auto planCoreDigest = root.get<std::string>("planCoreDigest");
  const auto modelManifestDigest = root.get<std::string>("modelManifestDigest");
  const auto protectionEpoch = root.get<std::string>("protectionEpoch");
  const auto nowMs = root.get<std::uint64_t>("nowMs");

  std::vector<std::uint8_t> publicKeyBytes;
  std::vector<std::uint8_t> seedBytes;
  BOOST_REQUIRE(publicKeyBytes.empty());
  for (std::size_t index = 0; index < authorityPublicKeyRaw.size(); index += 2) {
    publicKeyBytes.push_back(static_cast<std::uint8_t>(
      std::stoul(authorityPublicKeyRaw.substr(index, 2), nullptr, 16)));
  }
  for (std::size_t index = 0; index < recipientSeed.size(); index += 2) {
    seedBytes.push_back(static_cast<std::uint8_t>(
      std::stoul(recipientSeed.substr(index, 2), nullptr, 16)));
  }

  std::size_t checked = 0;
  for (const auto& item : root.get_child("cases")) {
    const auto caseValue = caseFrom(item.second, root);
    NativeRecipientKey recipient;
    recipient.kind = NativeRecipientKey::Kind::Ed25519Seed;
    recipient.material = std::string(
      reinterpret_cast<const char*>(seedBytes.data()), seedBytes.size());
    const auto result = verifyAndUnwrapNativeGrant(
      caseValue.wire,
      std::string(reinterpret_cast<const char*>(publicKeyBytes.data()),
                  publicKeyBytes.size()),
      recipient,
      providerIdentity, caseValue.requestId, caseValue.attempt,
      caseValue.planCoreDigest, caseValue.modelManifestDigest,
      caseValue.protectionEpoch, caseValue.nowMs);
    BOOST_TEST_MESSAGE("case=" << caseValue.name
                      << " ok=" << result.verified
                      << " reason=" << result.reason);
    BOOST_CHECK_MESSAGE(result.verified == caseValue.expectedOk,
                        caseValue.name << ": verified mismatch");
    if (caseValue.expectedOk) {
      std::ostringstream keyHex;
      for (auto byte : result.contentKey) {
        static constexpr char DIGITS[] = "0123456789abcdef";
        keyHex << DIGITS[byte >> 4] << DIGITS[byte & 0x0f];
      }
      BOOST_CHECK_MESSAGE(keyHex.str() == caseValue.expectedContentKey,
                          caseValue.name << ": content key mismatch");
    }
    else {
      BOOST_CHECK_MESSAGE(!result.reason.empty(),
                          caseValue.name << ": rejection has no reason");
    }
    ++checked;
  }
  BOOST_CHECK_EQUAL(checked, 9U);
}

BOOST_AUTO_TEST_CASE(NativeGrantVerifierRejectsMalformedWire)
{
  NativeRecipientKey recipient;
  recipient.kind = NativeRecipientKey::Kind::Ed25519Seed;
  recipient.material = std::string(32, 'a');
  const auto result = verifyAndUnwrapNativeGrant(
    "not json at all", std::string(32, 'b'), recipient,
    "/provider/p0", "req-1", 1,
    "sha256:" + std::string(64, 'c'), "sha256:" + std::string(64, 'd'),
    "spec180-yolo-protected-v1", 1000);
  BOOST_CHECK(!result.verified);
  BOOST_CHECK(result.reason.find("DI_PROTECTED_GRANT_REJECTED") !=
              std::string::npos);
}

BOOST_AUTO_TEST_CASE(NativeGrantVerifierRejectsWrongRecipientKeyKind)
{
  // The positive vector wire uses an X25519 envelope; handing it an EC
  // recipient must fail closed with a clear reason.
  const auto root = loadVectors();
  const auto authorityPublicKeyRaw =
    root.get<std::string>("authorityPublicKeyRaw");
  std::string wire;
  for (const auto& item : root.get_child("cases")) {
    if (item.second.get<std::string>("name") == "positive-roundtrip") {
      wire = item.second.get<std::string>("wire");
    }
  }
  BOOST_REQUIRE(!wire.empty());
  std::string publicKeyBytes;
  for (std::size_t index = 0; index < authorityPublicKeyRaw.size(); index += 2) {
    publicKeyBytes.push_back(static_cast<char>(
      std::stoul(authorityPublicKeyRaw.substr(index, 2), nullptr, 16)));
  }
  NativeRecipientKey recipient;
  recipient.kind = NativeRecipientKey::Kind::EcP256Pem;
  recipient.material = "not-a-pem";
  const auto result = verifyAndUnwrapNativeGrant(
    wire, publicKeyBytes, recipient,
    root.get<std::string>("providerIdentity"),
    root.get<std::string>("requestId"),
    root.get<std::uint64_t>("attempt"),
    root.get<std::string>("planCoreDigest"),
    root.get<std::string>("modelManifestDigest"),
    root.get<std::string>("protectionEpoch"),
    root.get<std::uint64_t>("nowMs") + 1000);
  BOOST_CHECK(!result.verified);
  BOOST_CHECK(result.reason.find("requires an Ed25519") !=
              std::string::npos);
}

} // namespace ndnsf::di::test
