#!/usr/bin/env python3
"""Build a content-addressed T009 preparation and generation source bundle."""

from __future__ import annotations

import argparse
import hashlib
import shutil
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[3]
FEATURE_ROOT = PROJECT_ROOT / "specs/162-itiger-qwen36-generation"
PIPELINE_ROOT = (
    PROJECT_ROOT / "examples/python/NDNSF-DistributedInference/llm_pipeline"
)
REPO_CLIENT_ROOT = (
    PROJECT_ROOT / "NDNSF-DistributedRepo/pythonWrapper/py_repoclient"
)
NDNSF_PYTHON_ROOT = PROJECT_ROOT / "pythonWrapper/ndnsf"
DI_PLACEMENT_ROOT = (
    PROJECT_ROOT
    / "NDNSF-DistributedInference/ndnsf_distributed_inference/app_sdk"
)
DI_APP_CLIENT_ROOT = (
    PROJECT_ROOT
    / "NDNSF-DistributedInference/ndnsf_distributed_inference/app_sdk"
)
DI_SDK_PLACEMENT_ROOT = (
    PROJECT_ROOT
    / "NDNSF-DistributedInference/ndnsf_distributed_inference/sdk"
)
DI_PROVIDER_ROOT = (
    PROJECT_ROOT
    / "NDNSF-DistributedInference/ndnsf_distributed_inference"
)
DI_QWEN_ADAPTER_ROOT = (
    PROJECT_ROOT
    / "NDNSF-DistributedInference/ndnsf_distributed_inference/adapters/qwen"
)
DI_PRESPLIT_ROOT = (
    PROJECT_ROOT
    / "NDNSF-DistributedInference/ndnsf_distributed_inference/planner"
)

SOURCES = {
    "contracts/generation-evidence.md":
        FEATURE_ROOT / "contracts/generation-evidence.md",
    "contracts/model-and-placement.md":
        FEATURE_ROOT / "contracts/model-and-placement.md",
    "contracts/prompt-set.json":
        FEATURE_ROOT / "contracts/prompt-set.json",
    **{
        f"jobs/{name}": FEATURE_ROOT / "jobs" / name
        for name in (
            "analyze-generation-formal.py",
            "analyze-generation-full-smoke.py",
            "analyze-generation-smoke.py",
            "build-automatic-planning-manifest.py",
            "build-generation-policy.py",
            "capacity-preflight.py",
            "generation-rank-inner.sh",
            "generation-rank.sh",
            "generation-smoke.sbatch",
            "nfd.conf.in",
            "prepare-qwen36.py",
            "prepare-reference.sbatch",
            "prepare-stages.sh",
            "register-qwen36-repo.py",
            "run-repo-node.py",
        )
    },
    **{
        f"llm_pipeline/{name}": PIPELINE_ROOT / name
        for name in (
            "deployment_control.py",
            "llm_pipeline_lib.py",
            "plan_pipeline.py",
            "provider.py",
            "user.py",
        )
    },
    **{
        f"runtime/py_repoclient/{name}": REPO_CLIENT_ROOT / name
        for name in (
            "__init__.py",
            "artifact_api.py",
            "artifact_lifecycle.py",
            "artifact_transfer.py",
            "network_artifact_backend.py",
            "orchestration.py",
            "persistence.py",
            "service_names.py",
        )
    },
    # Keep the installed NDNSF runtime's collaboration wait path aligned with
    # the source bundle.  generation-rank.sh binds this one module into the
    # native SIF; rebaking a 5+ GB image is unnecessary for Python-only fixes.
    "runtime/ndnsf-service.py": NDNSF_PYTHON_ROOT / "service.py",
    "runtime/di-placement.py": DI_PLACEMENT_ROOT / "placement.py",
    "runtime/app-sdk-client.py": DI_APP_CLIENT_ROOT / "client.py",
    "runtime/app-sdk-facades.py": DI_APP_CLIENT_ROOT / "facades.py",
    # The app-sdk placement module consumes ArtifactPreparationMode from this
    # contract module.  The sealed image predates REUSE_CACHED, so binding only
    # the coordinator leaves the post-ACK branch raising AttributeError("REUSE_CACHED")
    # immediately after the strategy decision.  Keep the enum and its data-only
    # placement contract from the same source identity as the coordinator.
    "runtime/sdk-placement.py": DI_SDK_PLACEMENT_ROOT / "placement.py",
    # The sealed image's installed DI provider module may lag the repository
    # source.  Bind the provider implementation used by the collaboration
    # response path so Selection/terminal-release fixes are actually live.
    "runtime/di-provider.py": DI_PROVIDER_ROOT / "provider.py",
    # The Qwen user imports its model-family adapter from the sealed image's
    # installed package.  Bind the current placement adapter as well, so its
    # dependency edges are sealed into the request-scoped tensor-* key scopes
    # generated by the current app-sdk placement implementation.  Without
    # this override a stale image adapter can publish symbolic pipeline-stage
    # scopes that have no corresponding encrypted key Data.
    "runtime/qwen-adapter-placement.py": DI_QWEN_ADAPTER_ROOT / "placement.py",
    # Apply the post-ACK cache/catalog binding in the installed planner
    # without rebuilding the foundation image.  A Provider's retained disk
    # bytes are not reusable until the current Repo exposes matching names.
    "runtime/presplit-first.py": DI_PRESPLIT_ROOT / "presplit_first.py",
}


class BundleError(RuntimeError):
    pass


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def build(output: Path) -> dict[str, object]:
    if output.exists() and any(output.iterdir()):
        raise BundleError("OUTPUT_DIRECTORY_NOT_EMPTY")
    output.mkdir(parents=True, exist_ok=True)

    rows: list[str] = []
    for relative, source in sorted(SOURCES.items()):
        if not source.is_file():
            raise BundleError(f"SOURCE_MISSING:{source}")
        target = output / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source, target)
        target.chmod(0o500 if target.suffix in {".py", ".sh"} else 0o400)
        rows.append(f"{sha256_file(target)}  {relative}\n")

    manifest = output / "source-files.sha256"
    manifest.write_text("".join(rows), encoding="utf-8")
    manifest.chmod(0o400)
    digest = sha256_file(manifest)
    return {
        "schemaVersion": "spec162-t009-live-source-bundle-v1",
        "sourceCount": len(SOURCES),
        "sourceManifestSha256": digest,
        "output": str(output),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    result = build(args.output)
    print(
        "T009_LIVE_SOURCE_BUNDLE_PASS "
        f"count={result['sourceCount']} "
        f"sha256={result['sourceManifestSha256']} "
        f"output={result['output']}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
